config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  resources :posts do
    get 'my', to: 'posts#my_posts', on: :collection
  end
  resources :comments, only: [:create, :edit, :update, :destroy]
  root 'posts#index'
  resources :tags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true, length: { minimum: 10 }

  default_scope -> { order('created_at') }
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 10, maximum: 200 }
  validates :body, presence: true, length: { minimum: 30 }

  default_scope -> { order('created_at DESC') }
  scope :public_posts, -> { where(public: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, foreign_key: :author_id

  validates :username, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?
  self.responder = ApplicationResponder
  respond_to :html

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def user_not_authorized
    flash[:alert] = 'Forbidden.'
    redirect_to(request.referrer || root_path)
  end

  def record_not_found
    flash[:alert] = 'Not found.'
    redirect_to action: :index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:create]
  before_action :load_comment, only: [:edit, :update, :destroy]

  respond_to :js, only: [:create]

  def create
    @comment = @post.comments.create(comment_params)
    respond_with(@comment)
  end

  def edit
    authorize(@comment)
    respond_with(@comment.post)
  end

  def update
    authorize(@comment)
    @comment.update(comment_params)
    if @comment.errors.present?
      respond_with(@comment)
    else
      redirect_to @comment.post
    end
  end

  def destroy
    authorize(@comment)
    @comment.destroy
    redirect_to @comment.post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def load_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text).merge(author_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.public_posts.includes(:author).page(params[:page])
    @tags = Post.tag_counts_on(:tags)
    respond_with(@posts)
  end

  def show
    authorize(@post)
    respond_with(@post)
  end

  def new
    @post = current_user.posts.new(public: true)
    respond_with(@post)
  end

  def create
    @post = current_user.posts.create(post_params)
    respond_with(@post)
  end

  def edit
    authorize(@post)
    respond_with(@post)
  end

  def update
    authorize(@post)
    @post.update(post_params.merge(date_from_string))
    respond_with(@post)
  end

  def destroy
    authorize(@post)
    @post.destroy
    respond_with(@post)
  end

  def my_posts
    @posts = current_user.posts.page(params[:page])
    respond_with(@posts)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :public, :tag_list)
  end

  def date_from_string
    { created_at: DateTime.strptime(params[:post][:created_at], '%d.%m.%Y %H:%M')}
  end

  def load_post
    @post = Post.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.public_posts.tagged_with(@tag.name).page(params[:page])
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def alerts(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
          class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    error_messages(resource)
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
  def error_messages(res)
    return "" if res.errors.empty?

    messages = res.errors.full_messages.map{ |msg| "<p>#{msg}.</p>"}.join

    html = <<-HTML
    <div class="alert alert-danger" id="error_explanation">      
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
  def date_format(date)
    date.strftime('%d.%m.%Y %H:%M')
  end
end

app/views/acts_as_taggable_on/tags/_tag.html.slim
= link_to tag.name, tag_path(tag)
|&nbsp

app/views/comments/create.js.erb
<% unless @comment.errors.present? %>
  $('.messages').append('<%= j render 'posts/comment', comment: @comment %>')
  $('.no-comments').hide()
  $('#comment_text').val('')
  $('.comment-errors').html('')
<% else %>
  $('.comment-errors').html('<%= j error_messages(@comment) %>')
<% end %>

app/views/comments/edit.html.slim
.page-header
  h3
    = t('.edit_comment')
.panel.panel-default
  .panel-body
    = error_messages(@comment)
    = form_for @comment do |f|
      .form-group
        = f.label :text, class: 'control-label'
        = f.text_area :text, class: 'form-control'
      = f.submit t('.update_comment'), class: 'btn btn-primary'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-static-top#main-navbar
  .container
    .navbar-header
      button.navbar-toggle.navbar-left.collapsed type="button" data-toggle="collapse" data-target="#navbar-collapse"
        i.icon-bar
        i.icon-bar
        i.icon-bar
      = link_to t('.main'), root_path, class: 'navbar-brand'
    .navbar-collapse.collapse.navbar-responsive-collapse#navbar-collapse
      - if user_signed_in?
        ul.nav.navbar-nav
          li
            = link_to t('.my_posts'), my_posts_path
          li
            = link_to t('.create_post'), new_post_path
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              = current_user.username
              |&nbsp
              i.caret
            ul.dropdown-menu
              li
                = link_to t('.change_password_email'), edit_user_registration_path
              li
                = link_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete

        - else
          li
            = link_to t('devise.sessions.new.sign_in'), new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SimpleBlog
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    .container
      = alerts
    .container
      = yield

app/views/posts/_comment.html.slim
p
  b
    = comment.author.username
  |&nbsp
  = date_format(comment.created_at)
  |&nbsp
  - if policy(comment).edit?
    = link_to t('.edit_comment'), edit_comment_path(comment), class: 'btn btn-primary btn-sm'
    |&nbsp
  - if policy(comment).destroy?
    = link_to t('.delete_comment'), comment_path(comment), method: :delete, class: 'btn btn-danger btn-sm'
p
  = simple_format(comment.text)

app/views/posts/_comments.html.slim
.page-header
  h3
    = t('.title')
.panel.panel-default
  .panel-body
    .messages
      - if @post.comments.present?
        - @post.comments.includes(:author).each do |comment|
          = render 'comment', comment: comment
      - else
        .no-comments
          p
            = t('.no_comments')
    - if user_signed_in?
      hr
      .comment-errors
      = form_for @post.comments.build, remote: true do |f|
        .form-group
          = f.text_area :text, class: 'form-control', placeholder: t('.text_placeholder')
          = hidden_field_tag :post_id, @post.id
        = f.submit t('.create_comment'), class: 'btn btn-primary'

app/views/posts/_form.html.slim
- new_record = post.new_record?
.page-header
  h3
    = new_record ? t('.new_post') : t('.edit_post')
.panel.panel-default
  .panel-body
    = error_messages(post)
    = form_for post do |f|
      .form-group
        = f.label :title, class: 'control-label'
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body, class: 'control-label'
        = f.text_area :body, class: 'form-control'
      - unless new_record
        .form-group
          .input-group.date#datetimepicker
            = f.text_field :created_at, value: date_format(post.created_at), class: 'form-control'
            span.input-group-addon
              span.glyphicon.glyphicon-calendar
      .form-group
        = f.label :tag_list, class: 'control-label'
        = f.text_field :tag_list, value: f.object.tag_list.to_s, class: 'form-control'
      .checkbox
        label
          = f.check_box :public
          = t('activerecord.attributes.post.public')
      = f.submit new_record ? t('.create_post') : t('.update_post'), class: 'btn btn-primary'

app/views/posts/_item.html.slim
tr
  td
    = link_to post.title, post_path(post)
  td
    = post.author.username
  td
    = date_format(post.created_at)
  - if my_posts
    td
      = post.public

app/views/posts/_table.html.slim
- unless defined?(my_posts)
  - my_posts = false
.panel.panel-default
  table.table.table-striped
    thead
      th
        = t('activerecord.attributes.post.title')
      th
        = t('activerecord.attributes.post.author')
      th
        = t('activerecord.attributes.post.created_at')
      - if my_posts
        th
          = t('activerecord.attributes.post.public')
    tbody
      - posts.each do |post|
        = render 'posts/item', post: post, my_posts: my_posts
= paginate(posts)

app/views/posts/edit.html.slim
= render 'posts/form', post: @post

app/views/posts/index.html.slim
.page-header
  h3
    = t('.title')
- if @posts.empty?
  h4
    = t('posts.no_posts')
- else
  = render 'posts/table', posts: @posts

#cloud
  - tag_cloud(@tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class|
    = link_to tag.name, tag_path(tag), class: css_class
    |&nbsp

app/views/posts/my_posts.html.slim
.page-header
  h3
    = t('.title')
- if @posts.empty?
  h4
    = t('posts.no_posts')
- else
  = render 'posts/table', posts: @posts, my_posts: true

app/views/posts/new.html.slim
= render 'posts/form', post: @post

app/views/posts/show.html.slim
.page-header
  h3
    = @post.title
p
  - if policy(@post).edit?
    = link_to t('.edit_post'), edit_post_path, class: 'btn btn-primary'
  |&nbsp
  - if policy(@post).destroy?
    = link_to t('.delete_post'), post_path(@post), method: :delete, class: 'btn btn-danger'
.panel.panel-default
  .panel-body
    = simple_format(@post.body)
    p
      = render @post.tags
= render 'posts/comments'

app/views/tags/show.html.slim
.page-header
  h3
    = @tag.name
= render 'posts/table', posts: @posts